### ISSUE TITLE
no such table: users_profile

### ISSUE THREAD

**Issue by Sinaatkd** [akhil-s-kumar/django-blog-app#5]
Hello
I am Cena
I wanted to participate in the project but when I wanted to create a superuser I got the following error
`no such table: users_profile`

**Comment by deejax** [comment]
Hi,
I faced the same issue. You should run migrations for the app users separately.  
`python manage.py migrate users`

**Comment by Sinaatkd** [comment]
Thanks

**Comment by deejax** [comment]
Also to warn you , the app is not complete :). But I really like the idea and the simple layout. @akhil-s-kumar It would be great if we can complete this together. I would be happy to contribute as well ,but I am still a beginner in django and not familiar with graphene .

**Comment by akhil-s-kumar** [comment]
Yeah I know it's not complete but for a beginner, it's fine to read the codebase and understand how it works. Yeah, you can contribute as well. The thing is it's not making use of GraphQL API as of now it's meant for fetching data from the backend for mobile app. But we can make use of it by migrating HTML templated to React/Next JS for WebApp and React Native/Flutter for Mobile app.

I'm happy to collaborate and work together :)

**Comment by Sinaatkd** [comment]
I also liked the general idea of ​​the project and decided to complete part of the project

**Comment by akhil-s-kumar** [comment]
Do one thing make issues and work on it make a pull request.
