### ISSUE TITLE
v1.2

### ISSUE THREAD

**Issue by nirajpoudel** [akhil-s-kumar/django-blog-app#7]
Where can i find v1.2 for this project? 

for now as a guest user I can login but can't edit my profile and create post.

**Comment by akhil-s-kumar** [comment]
Hi Niraj,

This repository itself is v1.2. If you want to edit a profile or create a post you have to do it from the backend since I haven't added those features to do it from the frontend itself. You can work on it and make a pull request.

Regards,
Akhil S Kumar
